name: flyer
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_size_text: ^3.0.0
  flutter_svg: ^2.0.9
  keyboard_detection: ^0.7.0
  path_provider: ^2.1.5
  google_fonts: ^6.2.1
  coderspace: ^1.0.12
  dio: ^5.9.0
  archive: ^4.0.7
  gallery_saver_plus: ^3.2.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/extra/
    - assets/card/